WebApp/protected/controllers/ImageController.php
<?php

class ImageController extends Controller
{
	const thumbSuffix = '_thumb';
	
 	public function filters()
    {
        return array(
            'accessControl',
        );
    }
    
	public function accessRules()
    {
        return array(
        	array('deny',
                'actions'=>array('delete', 'search', 'upload', 
                				 'get','getImageListXML'),
        		'users'=>array('?'),
            )
        );
    }


    
	public function actionDelete()
	{
		$result = "id field missing";
		if (isset($_REQUEST['id'])) {
			$imageId = (int)$_REQUEST['id'];
			//TODO: refactor not to fetch every item in user table, below line fetches everything
			$image = Upload::model()->with("user")-> findBypk($imageId);
			$result = "No image with specific id";
			if ($image != null)
			{
				$result = "not authorized to delete";
				if ($image->user->Id == Yii::app()->user->id )
				{
					$result = "An error occured 1";
					if ($image->delete()) {
						$result = 1;
						if (file_exists($this->getFileName($imageId))) {
							$result = "An error occured 2";
							if (unlink($this->getFileName($imageId))) {
								$result = 1;
								if (file_exists($this->getFileName($imageId))) {
									$result = "An error occured 3";
									if (unlink($this->getFileName($imageId))) {
										$result = 1;
									}
								}
							}
						}
							
					}
				}
			}
		}
		echo CJSON::encode(array("result"=> $result));
		Yii::app()->end();
	}

	public function actionGetList()
	{

		if(Yii::app()->user->id != null)
		{
			$friendList = AuxiliaryFriendsOperator::getFriendIdList();
			
			$sqlCount = 'SELECT count(*)
						 FROM '. Upload::model()->tableName() . ' u 
						 WHERE userId in ('. $friendList .') 
						 		OR userId = '. Yii::app()->user->id .' OR 
						 		publicData = 1';
	
			$count=Yii::app()->db->createCommand($sqlCount)->queryScalar();
	
			$sql = 'SELECT u.Id as id, u.description, s.realname, s.Id as userId
						 FROM '. Upload::model()->tableName() . ' u 
						 LEFT JOIN  '. Users::model()->tableName() . ' s ON s.Id = u.userId
						 WHERE userId in ('. $friendList .') OR 
						 	   userId = '. Yii::app()->user->id .' OR 
						 	   publicData = 1
						  ORDER BY u.Id DESC';

	
			$dataProvider = new CSqlDataProvider($sql, array(
			    											'totalItemCount'=>$count,
														    'sort'=>array(
							        							'attributes'=>array(
							             									'id',
																			),
															),
														    'pagination'=>array(
														        'pageSize'=>Yii::app()->params->imageCountInOnePage,
															),
													));		
		}
		else
		{
			$dataProvider = null;
		}
	
		Yii::app()->clientScript->scriptMap['jquery.js'] = false;
		//TODO: added below line because gridview.js is loaded before.
		Yii::app()->clientScript->scriptMap['jquery.yiigridview.js'] = false;
		$this->renderPartial('imagesInfo',array('dataProvider'=>$dataProvider,'model'=>new SearchForm(),'imageList'=>true), false, true);
	}

	public function actionSearch() {
		$model = new SearchForm();

		$dataProvider = null;
		if(isset($_REQUEST['SearchForm']))
		{
			$model->attributes = $_REQUEST['SearchForm'];
			if ($model->validate()) {

				$friendList = AuxiliaryFriendsOperator::getFriendIdList();
				
				$sqlCount = 'SELECT count(*)
					 FROM '. Upload::model()->tableName() . ' u
					 LEFT JOIN  '. Users::model()->tableName() . ' s ON s.Id = u.userId 
					 WHERE (u.userId in ('. $friendList .') 
					 			OR 
						 		u.userId = '. Yii::app()->user->id .'
						 		OR
						 		u.publicData = 1 )
					 	   AND	
					 	   (s.realname like "%'. $model->keyword .'%"
						   		OR
						   		u.description like "%'. $model->keyword.'%")';

				$count=Yii::app()->db->createCommand($sqlCount)->queryScalar();

				$sql ='SELECT u.Id as id, u.description, s.realname, s.Id as userId
					 FROM '. Upload::model()->tableName() . ' u
					 LEFT JOIN  '. Users::model()->tableName() . ' s ON s.Id = u.userId 
					 WHERE (u.userId in ('. $friendList .') 
					 			OR 
						 		u.userId = '. Yii::app()->user->id .' 
						 		OR
						 		u.publicData = 1)
					 	   AND
					 	   (s.realname like "%'. $model->keyword .'%"
					 			OR
					 	   		u.description like "%'. $model->keyword.'%")';

				$dataProvider = new CSqlDataProvider($sql, array(
		    											'totalItemCount'=>$count,
													    'sort'=>array(
						        							'attributes'=>array(
						             									'id', 'realname',
															),
														),
													    'pagination'=>array(
													        'pageSize'=>Yii::app()->params->imageCountInOnePage,
															'params'=>array(CHtml::encode('SearchForm[keyword]')=>$model->attributes['keyword']),
														),
								));
					
			}
		}
		Yii::app()->clientScript->scriptMap['jquery.js'] = false;
		//TODO: added below line because gridview.js is loaded before.
		Yii::app()->clientScript->scriptMap['jquery.yiigridview.js'] = false;
		$this->renderPartial('searchImageResults', array('model'=>$model, 'dataProvider'=>$dataProvider), false, true);
	}

	public function actionGet()
	{
		if (!isset($_REQUEST['id'])) {
			echo "No id";
			Yii::app()->end();
		}
		$imageId = (int) $_REQUEST['id'];

		$fileName = $this->getFileName($imageId);
		if (file_exists($fileName) === true){
			$thumb = false;
			if (isset($_REQUEST['thumb'])) {
				$thumb = true;
			}
			if ($thumb == true) {
				$fileName = $this->getFileName($imageId, true);;
				if (file_exists($fileName) === false) {
					$this->createThumb($imageId);
				}
			}

		}
		else {
			$fileName = Yii::app()->basePath . DIRECTORY_SEPARATOR . '..' . DIRECTORY_SEPARATOR . 'images/image_missing.png';
		}
		header('Content-Type: image/jpeg;');
		echo file_get_contents($fileName);

		Yii::app()->end();
	}

	/**
	 * this action is used by mobile clients
	 */
	public function actionUpload()
	{		
		$result = "Missing parameter";		
		if (isset($_FILES["image"])
			&& isset($_REQUEST['latitude']) && $_REQUEST['latitude'] != NULL
			&& isset($_REQUEST['longitude']) && $_REQUEST['longitude'] != NULL
			&& isset($_REQUEST['altitude']) && $_REQUEST['altitude'] != NULL
			&& isset($_REQUEST['description']) && $_REQUEST['description'] != NULL)
		{
			$result = "Upload Error";
			if ($_FILES["image"]["error"] == UPLOAD_ERR_OK )
			{
				$latitude = (float) $_REQUEST['latitude'];
				$longitude = (float) $_REQUEST['longitude'];
				$altitude = (float) $_REQUEST['altitude'];
				$description = htmlspecialchars($_REQUEST['description']);

				$publicData = 0;
				if (isset($_REQUEST['publicData']) && $_REQUEST['publicData'] != NULL) {
					$tmp = (int) $_REQUEST['publicData'];
					if ($tmp == 1) {
						$publicData = 1;
					}
				}

				if (Yii::app()->user->id != null) 
				{
					
					$sql = sprintf('INSERT INTO '
									. Upload::model()->tableName() .'
									(userId, latitude, longitude, altitude, uploadtime, publicData, description)
									VALUES(%d, %s, %s, %s, NOW(), %d, "%s")', 
									Yii::app()->user->id, $latitude, $longitude, $altitude, $publicData, $description);
					$result = "Unknown Error";
					$effectedRows = Yii::app()->db->createCommand($sql)->execute();
					if ($effectedRows == 1)
					{
						$result = "Error in moving uploading file";
						if (move_uploaded_file($_FILES["image"]["tmp_name"], Yii::app()->params->uploadPath .'/'. Yii::app()->db->lastInsertID . '.jpg'))
						{
							$result = "1";
						}
					}
				}
		
			}

		}
		echo CJSON::encode(array("result"=> $result));
		Yii::app()->end();

	}

	private function getFileName($imageId, $thumb = false)
	{
		$fileName = Yii::app()->params->uploadPath. '/' . $imageId . '.jpg';
		if ($thumb == true) {
			$fileName = Yii::app()->params->uploadPath . '/' . $imageId . self::thumbSuffix .'.jpg';
		}
		return $fileName;
	}

	private function createThumb($imageId) {

		// Set maximum height and width
		$width  = 36;
		$height = 36;
		$filename =  $this->getFileName($imageId);
		if (file_exists($filename) === true) {
			// Get new dimensions
			list($width_orig, $height_orig) = getimagesize($filename);

			$width = ($height / $height_orig) * $width_orig;


			// Resample
			$image_p = imagecreatetruecolor($width, $height);
			$image   = imagecreatefromjpeg($filename);
			imagecopyresampled($image_p, $image, 0, 0, 0, 0, $width, $height, $width_orig, $height_orig);
			$filenameThumb =  $this->getFileName($imageId, true);
			touch($filenameThumb);
			// Output
			imagejpeg($image_p, $filenameThumb);
			imagedestroy($image);
		}

	}

	public function actionGetImageListXML()
	{
		if (Yii::app()->user->isGuest) {
			return;
		}
		$pageNo = 1;
		if (isset($_REQUEST['pageNo']) && $_REQUEST['pageNo'] > 0) {
			$pageNo = (int) $_REQUEST['pageNo'];
		}
		$offset = ($pageNo - 1) * Yii::app()->params->itemCountInDataListPage;
		$out = '';
		$dataFetchedTimeKey = "ImageController.dataFetchedTime";
		if (isset($_REQUEST['list'])) {
			if ($_REQUEST['list'] == "onlyUpdated")
			{
				$time = Yii::app()->session[$dataFetchedTimeKey];
				if ($time !== false && $time != "")
				{
					$friendList = AuxiliaryFriendsOperator::getFriendIdList();
					$sqlCount = 'SELECT ceil(count(*)/'. Yii::app()->params->itemCountInDataListPage .')
								 FROM '. Upload::model()->tableName() . ' u 
								 WHERE (userId in ('. $friendList .') 
								        OR userId = '. Yii::app()->user->id .'
								        OR publicData = 1)
								        AND unix_timestamp(u.uploadTime) >= '. $time;
						
					$pageCount=Yii::app()->db->createCommand($sqlCount)->queryScalar();
						
					$sql = 'SELECT u.Id as id, u.description, s.realname, s.Id as userId, date_format(u.uploadTime,"%d %b %Y %T") as uploadTime, u.altitude, u.latitude, u.longitude
								 FROM '. Upload::model()->tableName() . ' u 
								 LEFT JOIN  '. Users::model()->tableName() . ' s ON s.Id = u.userId
								 WHERE (userId in ('. $friendList .') 

WebApp/protected/views/image/_image.php
<div>
    <a href="javascript:TRACKER.showImageWindow(<?php echo $data["id"]; ?>)"><img src="<?php echo $this->createUrl("image/get", array(
														 'id'=>$data["id"],
														 'thumb'=>'ok'
														)
										  );?>" />
		Image sender:<?php echo $data['realname']; ?>
   </a>
		<?php 
			if ($data['userId'] == Yii::app()->user->id) {
				echo CHtml::ajaxLink('Delete', $this->createUrl('image/delete', array('id'=>$data["id"])), 
 										array(
				 							'success'=>'function(result){ 
				 														  try {
				 																var obj = jQuery.parseJSON(result);
																				if (obj.result && obj.result == "1") {
																					alert("operation successfull")
																				}
																				else {
																					alert(obj.result);
																				}
																		  }
																		  catch(error) {
																		  	alert(error);
																		  }
																		}',
											), 
										array()
									); 
			}
		?>
</div>

WebApp/protected/views/image/delete.php
<?php
$this->breadcrumbs=array(
	'Image'=>array('/image'),
	'Delete',
);?>
<h1><?php echo $this->id . '/' . $this->action->id; ?></h1>

<p>
	You may change the content of this page by modifying
	the file <tt><?php echo __FILE__; ?></tt>.
</p>

WebApp/protected/views/image/getList.php
<?php		
if ($dataProvider != null) {
	
	if (isset($imageList) && $imageList == true) {
		echo "<div id='imageId' style='display:none'></div>";
		$this->beginWidget('zii.widgets.jui.CJuiDialog', array(
		    'id'=>'imageDeleteConfirmation',
			// additional javascript options for the dialog plugin
		    'options'=>array(
		        'title'=>Yii::t('general', 'Delete Image'),
		        'autoOpen'=>false,
		        'modal'=>true, 
				'resizable'=>false,
				'buttons' =>array (
					"OK"=>"js:function(){
									". CHtml::ajax(
											array(
													'url'=>Yii::app()->createUrl('image/delete'),
													'data'=> array('id'=>"js:$('#imageId').html()"),
													'success'=> 'function(result) { 	
																 	try {
																 		$("#imageDeleteConfirmation").dialog("close");
																		var obj = jQuery.parseJSON(result);
																		if (obj.result && obj.result == "1") 
																		{
																			$.fn.yiiGridView.update("imageListView");
																		}
																		else 
																		{
																			$("#messageDialogText").html("Sorry,an error occured in operation");
																			$("#messageDialog").dialog("open");
																		}
	
																	}
																	catch(ex) {
																		$("#messageDialogText").html("Sorry,an error occured in operation");
																		$("#messageDialog").dialog("open");
																	}
																}',
												)) .
								"}",
					"Cancel"=>"js:function() {
						$( this ).dialog( \"close\" );
					}" 
					)),
				));
		echo "Do you want to delete this image?";
		$this->endWidget('zii.widgets.jui.CJuiDialog');
	}
	$this->widget('zii.widgets.grid.CGridView', array(
		    'dataProvider'=>$dataProvider,
	 		'id'=>'imageListView',
			'summaryText'=>'',
			'pager'=>array( 
				 'header'=>'',
		         'firstPageLabel'=>'',
		         'lastPageLabel'=>'',
			       ),
		    'columns'=>array(
				array(            // display 'create_time' using an expression
		          
					'type' => 'raw',
		            'value'=>'CHtml::link("<img src=\"".Yii::app()->createUrl("image/get", array(
														 "id"=>$data["id"],
														 "thumb"=>"ok"
														)
										  			)."\"  />", "#",
										array("onclick"=>"TRACKER.showImageWindow(".$data["id"].");")
					  				  )',
				),
				array(            // display 'create_time' using an expression
		            'name'=>'Description',
					'type' => 'raw',
		            'value'=>'CHtml::link($data["description"], "#", array(
    										"onclick"=>"TRACKER.showImageWindow(".$data["id"].");",
										))',	
				),
				array(            // display 'create_time' using an expression
		            'name'=>'Sender',
					'type' => 'raw',
		            'value'=>'CHtml::link($data["realname"], "#", array(
    										"onclick"=>"TRACKER.trackUser(".$data["userId"].");",
										))',
					//'htmlOptions'=>array('style'=>'width:160px;'),	
				),
				array(           
		        //    'name'=>'realname',
					'type' =>'raw',
		            'value'=>' ($data["userId"] == Yii::app()->user->id) 
		            			?
		            					CHtml::link("<img src=\"images/delete.png\"  />", "#", array(
		            						"onclick"=>"$(\"#imageId\").html(". $data["id"] .");
		            									$(\"#imageDeleteConfirmation\").dialog(\"open\");", "class"=>"vtip", "title"=>"Delete Photo"
		            						))
		            			: ""; ',
					'htmlOptions'=>array('width'=>'16px'),
				),

			),
	));
	
	

}
?>

WebApp/protected/views/image/imagesInfo.php
<?php if (Yii::app()->user->isGuest == false) { ?>
	<div class="form">
	<?php $form=$this->beginWidget('CActiveForm', array(
		'id'=>'searchImage-form',
		'enableClientValidation'=>true,
		'clientOptions'=> array(
							'validateOnSubmit'=> true,
							'validateOnChange'=>false,
						 ),
	
		));
		 ?>
		<div class="row">
			<?php	echo $form->textField($model,'keyword', array('class'=>'searchBox')); ?>
	
			<?php  echo CHtml::ajaxSubmitButton('Search', $this->createUrl('image/search'), 
												array(
													'complete'=> 'function() { $("#imageSearchResults").dialog("open"); return false;}',
													'update'=> '#imageSearchResults',
													 ),
												array(
													'id'=>'searchImageButton'
							 					));
				?>
			<?php echo $form->error($model,'keyword'); 	?>
		</div>
	<?php $this->endWidget(); ?>
	</div>
<?php } ?>
<?php 
	if (isset($dataProvider)) {
		$params = array('dataProvider'=>$dataProvider);
		if (isset($imageList) && $imageList == true) {
			$params = array_merge($params, array('imageList'=>true));
		}
		$this->renderPartial('getList', $params, false, true);
	}
	else
	{
		echo 'No photos to show... <br/> <br/>';			
	}
	
	echo '<div id="imageSearchResults"></div>';
?>

WebApp/protected/views/image/search.php
<div class="form">
<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'searchImage-form',
	'enableClientValidation'=>true,
	'clientOptions'=> array(
						'validateOnSubmit'=> true,
						'validateOnChange'=>true,
					 ),

	));
	 ?>


	<div class="row">
		<?php echo $form->labelEx($model,'keyword'); ?>
		<?php echo $form->textField($model,'keyword'); ?>
		<?php echo CHtml::ajaxSubmitButton('Submit', $this->createUrl('image/search'), 
											array(
												'update'=> '#imageSearch',
												 ),
											null);?>
		<?php echo $form->error($model,'keyword'); 	?>
	</div>

<?php $this->endWidget(); ?>
</div>

<?php 
	if (isset($dataProvider)) {
		$this->renderPartial('getList', array('dataProvider'=>$dataProvider), false, true);
	}
?>

WebApp/protected/views/image/searchImageResults.php
<?php 
$this->beginWidget('zii.widgets.jui.CJuiDialog', array(
	    'id'=>'imageSearchResults',
	    // additional javascript options for the dialog plugin
	    'options'=>array(
	        'title'=>Yii::t('general', 'Search Results'),
	        'autoOpen'=>false,
	        'modal'=>true, 
			'resizable'=>false      
	    ),
	));

	if (isset($dataProvider)) {
		$this->renderPartial('getList', array('dataProvider'=>$dataProvider), false, true);
	}

	$this->endWidget('zii.widgets.jui.CJuiDialog');
?>